[build]
  command = "CI= npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://NEWSSYSTEM.herokuapp.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
